UI/app/config/routes.rb
require 'api_constraints' # File for API Scope Configuration

Comtor::Application.routes.draw do

  get "pages/home"
  get "pages/find"
  get "pages/leaderboard"
  get "pages/welcome"
  
  match "home" => "pages#home"
  match "find" => "pages#find"
  match "leaderboard" => "pages#leaderboard"

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
    
  # Set root path
  root :to => "pages#welcome"
  

  resources :opencomments
  resources :evaluations
  
  resources :chunks do
    # Post Method for AJAX Ratings
    member do
      post 'rate'
    end
    resources :opencomments, :evaluations
  end

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :opencomments, :chunks
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
end

UI/app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

UI/app/app/views/welcome/index.html.erb
<div class="row">
	<div class="span12">
	<p id="notice"><%= notice %></p>

	<p>
	  <b>Comment:</b>
	  <%= @chunk.comment %>
	</p>

	<p>
	  <b>Code:</b>
	  <%= @chunk.code %>
	</p>

	<%= link_to 'Edit', edit_chunk_path(@chunk) %> |
	<%= link_to 'Back', chunks_path %>

	<hr />

	<h1>New Comment</h1>

	<%= form_for [@opencomment] do |f| %>
	  <% if @opencomment.errors.any? %>
	    <div class="error_messages">
	      <h2>Please correct the following errors.</h2>
	      <ul>
	      <% @opencomment.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="field">
	    <%= f.text_area :comment, :rows => 8 %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>

	</div>
</div>