UI/app/config/routes.rb
require 'api_constraints' # File for API Scope Configuration

Comtor::Application.routes.draw do

  get "pages/home"
  get "pages/find"
  get "pages/leaderboard"
  get "pages/welcome"
  
  match "home" => "pages#home"
  match "find" => "pages#find"
  match "leaderboard" => "pages#leaderboard"

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
    
  # Set root path
  root :to => "pages#welcome"
  

  resources :opencomments
  resources :evaluations
  
  resources :chunks do
    # Post Method for AJAX Ratings
    member do
      post 'rate'
    end
    resources :opencomments, :evaluations
  end

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :opencomments, :chunks
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
end

UI/app/app/models/opencomment.rb
class Opencomment < ActiveRecord::Base
  belongs_to :chunk
  belongs_to :user
  
  attr_accessible :body, :commenter, :chunk, :user
end

UI/app/app/controllers/api/v1/opencomments_controller.rb
module Api
  module V1
    class OpencommentsController < ApplicationController
      respond_to :json
      
      # List All Opencomments
      def index
        respond_with Opencomment.all
      end
      
      # Show Specific Opencomment
      def show
        respond_with Opencomment.find(params[:id])
      end
      
      # Create a new Opencomment
      def create
        respond_with Opencomment.create(params[:opencomment])
      end
      
      # Update a Specific Opencomment
      def update
        respond_with Opencomment.update(params[:id], params[:opencomments])
      end
      
      # Destroy a Specific Opencomment
      def destroy
        respond_with Opencomment.destroy(params[:id])
      end

    end
  end
end

UI/app/app/controllers/opencomments_controller.rb
class OpencommentsController < ApplicationController
    # Create new opencomment from chunk
    def create
      @chunk = Chunk.find(params[:chunk_id])
      @opencomment = @chunk.opencomments.create(params[:opencomment])
      @opencomment.user_id = current_user.id
      @opencomment.save!
      redirect_to chunk_path(@chunk)
    end
    
    # New opencomment from chunk
    def new
      @Chunk = Chunk.find(params[:chunk_id])
      @opencomment = Opencomment.new(:chunk => @Chunk)

      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @Chunk }
      end
    end
end

UI/app/app/helpers/opencomments_helper.rb
module OpencommentsHelper
end

UI/app/app/views/opencomments/_form.html.erb
<%= simple_form_for(@opencomment) do |f| %>
  <%= f.error_notification %>

  <%= f.button :submit %>

  <div class="form-inputs">
  	<!-- For Chunk ID to match opencomment to -->
  	<%= hidden_field_tag :chunk_id,  :value  => @Chunk.id %>
  	<%= hidden_field_tag :commenter, :value  => current_user.email  %>
  	<%= f.input :body, :label => "Opencomment" %>
  </div>
<% end %>

UI/app/app/views/opencomments/edit.html.erb
<h1>Editing opencomment</h1>

<%= render 'form' %>

<%= link_to 'Show', @opencomment %> |
<%= link_to 'Back', opencomments_path %>

UI/app/app/views/opencomments/index.html.erb
<h1>Listing opencomments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @opencomments.each do |opencomment| %>
  <tr>
    <td><%= link_to 'Show', opencomment %></td>
    <td><%= link_to 'Edit', edit_opencomment_path(opencomment) %></td>
    <td><%= link_to 'Destroy', opencomment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Opencomment', new_opencomment_path %>

UI/app/app/views/opencomments/new.html.erb
<h3>Adding Opencomment for Chunk #<%= @Chunk.id %></h3>

<%= link_to 'Back', request.env['HTTP_REFERER'], :class => "btn"  %>

<div style="margin-top: 10px;" class="row">
    <div class="span8">
        <%= render 'form' %>
        <%= raw Pygments.highlight(@Chunk.code, lexer: 'java') %>
    </div>
</div>

UI/app/app/views/opencomments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_opencomment_path(@opencomment) %> |
<%= link_to 'Back', opencomments_path %>