UI/app/config/routes.rb
require 'api_constraints' # File for API Scope Configuration

Comtor::Application.routes.draw do

  get "pages/home"
  get "pages/find"
  get "pages/leaderboard"
  get "pages/welcome"
  
  match "home" => "pages#home"
  match "find" => "pages#find"
  match "leaderboard" => "pages#leaderboard"

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
    
  # Set root path
  root :to => "pages#welcome"
  

  resources :opencomments
  resources :evaluations
  
  resources :chunks do
    # Post Method for AJAX Ratings
    member do
      post 'rate'
    end
    resources :opencomments, :evaluations
  end

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :opencomments, :chunks
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
end

UI/app/app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :chunk
  belongs_to :user
  
  attr_accessible :attribute_one, :attribute_two, :attribute_three, :attribute_four, :attribute_five, :chunk, :user

  #validates_numericality_of :n, :only_integer => true, :message => "Only whole numbers allowed."
  #validates_inclusion_of :n, :in => 0..5, :message => "Must be between 0 and 5"
end

UI/app/app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  # Create new opencomment from chunk
  def create
    @chunk = Chunk.find(params[:chunk_id])
    @user = current_user
    @evaluation = @chunk.evaluations.create(params[:evaluation])
    @evaluation.user_id = current_user.id
    @evaluation.save!

    redirect_to chunk_path(@chunk)
  end
  
  # New opencomment from chunk
  def new
    @Chunk = Chunk.find(params[:chunk_id])
    @evaluation = Evaluation.new(:chunk => @Chunk)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @Chunk }
    end
  end

  # Delete an evaluation
  def destroy
    @Evaluation = Evaluation.find(params[:id])
    @Evaluation.destroy

    respond_to do |format|
      format.html { redirect_to chunks_url }
      format.json { head :no_content }
    end
  end
end

UI/app/app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

UI/app/app/views/evaluations/_form.html.erb
<%= simple_form_for(@evaluation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <label>Attribute #1</label>
    <%= f.number_field :attribute_one, :in => 0...6 %>
    <label>Attribute #2</label>
    <%= f.number_field :attribute_two, :in => 0...6 %>
    <label>Attribute #3</label>
    <%= f.number_field :attribute_three, :in => 0...6 %>
    <label>Attribute #4</label>
    <%= f.number_field :attribute_four, :in => 0...6 %>
    <label>Attribute #5</label>
    <%= f.number_field :attribute_five, :in => 0...6 %>

    <%= hidden_field_tag :user_id, value = current_user.id %>
    <%= hidden_field_tag :chunk_id, value = @Chunk.id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

UI/app/app/views/evaluations/_rating.html.erb
<label>Attribute 1:</label>
<%= ratings_for @Chunk, :dimension => :attr1 %>

<label>Attribute 2:</label>
<%= ratings_for @Chunk, :dimension => :attr2 %>

<label>Attribute 3:</label>
<%= ratings_for @Chunk, :dimension => :attr3 %>

<label>Attribute 4:</label>
<%= ratings_for @Chunk, :dimension => :attr4 %>

<label>Attribute 5:</label>
<%= ratings_for @Chunk, :dimension => :attr5 %>

UI/app/app/views/evaluations/edit.html.erb
<h1>Editing evaluation</h1>

<%= render 'form' %>

<%= link_to 'Show', @evaluation %> |
<%= link_to 'Back', evaluations_path %>

UI/app/app/views/evaluations/index.html.erb
<h1>Listing evaluations</h1>

<table>
  <tr>
    <th>Attribute one</th>
    <th>Attribute two</th>
    <th>Attribute three</th>
    <th>Attribute four</th>
    <th>Attribute five</th>
    <th>User</th>
    <th>Chunk</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @evaluations.each do |evaluation| %>
  <tr>
    <td><%= evaluation.attribute_one %></td>
    <td><%= evaluation.attribute_two %></td>
    <td><%= evaluation.attribute_three %></td>
    <td><%= evaluation.attribute_four %></td>
    <td><%= evaluation.attribute_five %></td>
    <td><%= evaluation.user_id %></td>
    <td><%= evaluation.chunk_id %></td>
    <td><%= link_to 'Show', evaluation %></td>
    <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
    <td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evaluation', new_evaluation_path %>

UI/app/app/views/evaluations/new.html.erb
<h1>New evaluation</h1> 

<%= link_to 'Back', request.env['HTTP_REFERER'], :class => "btn"  %>

<div style="margin-top: 10px;" class="row">
	<div class="span8">
		<%= raw Pygments.highlight(@Chunk.comment + @Chunk.code, lexer: 'java') %>
	</div>
	<div class="span2 well">
		<%= render 'rating' %>
	</div>
</div>

UI/app/app/views/evaluations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Attribute one:</b>
  <%= @evaluation.attribute_one %>
</p>

<p>
  <b>Attribute two:</b>
  <%= @evaluation.attribute_two %>
</p>

<p>
  <b>Attribute three:</b>
  <%= @evaluation.attribute_three %>
</p>

<p>
  <b>Attribute four:</b>
  <%= @evaluation.attribute_four %>
</p>

<p>
  <b>Attribute five:</b>
  <%= @evaluation.attribute_five %>
</p>

<p>
  <b>User:</b>
  <%= @evaluation.user_id %>
</p>

<p>
  <b>Chunk:</b>
  <%= @evaluation.chunk_id %>
</p>


<%= link_to 'Edit', edit_evaluation_path(@evaluation) %> |
<%= link_to 'Back', evaluations_path %>