UI/app/config/routes.rb
require 'api_constraints' # File for API Scope Configuration

Comtor::Application.routes.draw do

  get "pages/home"
  get "pages/find"
  get "pages/leaderboard"
  get "pages/welcome"
  
  match "home" => "pages#home"
  match "find" => "pages#find"
  match "leaderboard" => "pages#leaderboard"

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
    
  # Set root path
  root :to => "pages#welcome"
  

  resources :opencomments
  resources :evaluations
  
  resources :chunks do
    # Post Method for AJAX Ratings
    member do
      post 'rate'
    end
    resources :opencomments, :evaluations
  end

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :opencomments, :chunks
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
end

UI/app/app/models/chunk.rb
class Chunk < ActiveRecord::Base
  # Has many relationship with opencomments, will delete upon chunk destruction
  has_many :opencomments
  has_many :evaluations

  # Before destruction check that no opencomments are references so they are not lost
  before_destroy :ensure_not_referenced_by_any_opencomment

  # Accessible Model Attributes
  attr_accessible :code, :comment, :opencomment, :evaluation

  # Model Validation
  validates :code, :comment, presence: true

  # Ajaxful Rating
  ajaxful_rateable :dimensions => [:attr1, :attr2, :attr3, :attr4, :attr5]
  
  # Private Method Scope
  private
  # Reference checking method
  def ensure_not_referenced_by_any_opencomment
  	if opencomments.empty?
  		return true
  	else
  		errors.add(:base, 'Opencomments are present')
  		return false
  	end
  end
end

UI/app/app/controllers/api/v1/chunks_controller.rb
module Api
  module V1
    class ChunksController < ApplicationController
      respond_to :json
      
      # List All Chunks
      def index
        respond_with Chunk.all
      end
      
      # Show Specific Chunk
      def show
        respond_with Chunk.find(params[:id])
      end
      
      # Create a new Chunk
      def create
        respond_with Chunk.create(params[:chunk])
      end
      
      # Update a Specific Chunk
      def update
        respond_with Chunk.update(params[:id], params[:chunks])
      end
      
      # Destroy a Specific Chunk
      def destroy
        respond_with Chunk.destroy(params[:id])
      end

    end
  end
end

UI/app/app/controllers/chunks_controller.rb
class ChunksController < ApplicationController
  before_filter :authenticate_user!

  # Evaluate Code Chunk
  def eval
  end

  # Rate Code Chunk
  def rate
    @chunk = Chunk.find(params[:id])
    @chunk.rate(params[:stars], current_user, params[:dimension])
    render :update do |page|
      page.replace_html @chunk.wrapper_dom_id(params), ratings_for(@chunk, params.merge(:wrap => false))
      page.visual_effect :highlight, @chunk.wrapper_dom_id(params)
    end
  end
  
  # Comment Code Chunk
  def comment
  end

  # GET /chunks
  # GET /chunks.json
  # Show all Chunks
  def index
    @chunks = Chunk.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @chunks }
    end
  end

  # GET /chunks/1
  # GET /chunks/1.json
  # Show a Chunk
  def show
    @chunk = Chunk.find(params[:id])
    @Opencomments = Opencomment.all
    @Evaluations = Evaluation.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => { 
                                      :chunk          => @Chunk, 
                                      :opencomments   => @Opencomments,
                                      :evaluations    => @Evaluations,
                                    }}
    end
  end

  # GET /chunks/new
  # GET /chunks/new.json
  # Create a new chunk
  def new
    @Chunk = Chunk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @Chunk }
    end
  end

  # GET /chunks/1/edit
  # Edit a chunk
  def edit
    @Chunk = Chunk.find(params[:id])
    @Opencomment = Opencomment.new( :chunk => @chunk )

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => { :chunk        => @Chunk, 
                                      :opencomment  => @Opencomment }}
    end
  end

  # POST /chunks
  # POST /chunks.json
  # Create a chunk
  def create
    @Chunk = Chunk.new(params[:Chunk])

    respond_to do |format|
      if @Chunk.save
        format.html { redirect_to @Chunk, :notice => 'Chunk was successfully created.' }
        format.json { render :json => @Chunk, :status => :created, :location => @Chunk }
      else
        format.html { render :action => "new" }
        format.json { render :json => @Chunk.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /chunks/1
  # PUT /chunks/1.json
  # Put a chunk
  def update
    @Chunk = Chunk.find(params[:id])

    respond_to do |format|
      if @Chunk.update_attributes(params[:Chunk])
        format.html { redirect_to @Chunk, :notice => 'Chunk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @Chunk.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chunks/1
  # DELETE /chunks/1.json
  # Delete a chunk
  def destroy
    @Chunk = Chunk.find(params[:id])
    @Chunk.destroy

    respond_to do |format|
      format.html { redirect_to chunks_url }
      format.json { head :no_content }
    end
  end
end

UI/app/app/views/chunks/_form.html.erb
<%= simple_form_for @Chunk, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :comment %>
  <%= f.input :code %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                chunks_path, :class => 'btn' %>
  </div>
<% end %>

UI/app/app/views/chunks/edit.html.erb
<%- model_class = Chunk -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

UI/app/app/views/chunks/index.html.erb
<%- model_class = Chunk -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @chunks.each do |chunk| %>
      <tr>
        <td><%= link_to chunk.id, chunk_path(chunk) %></td>
        <td><%=l chunk.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
            chunk_path(chunk), :class => 'btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_chunk_path(chunk), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      chunk_path(chunk),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <a href="chunks/<%= chunk.id %>/opencomments/new" class="btn btn-mini">Comment</a>
          <a href="chunks/<%= chunk.id %>/evaluations/new" class="btn btn-mini">Evaluate</a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_chunk_path,
            :class => 'btn btn-primary' %>

UI/app/app/views/chunks/new.html.erb
<%- model_class = Chunk -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

UI/app/app/views/chunks/show.html.erb
<%- model_class = Chunk -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
  <%= link_to t('.back', :default => t("helpers.links.back")),
            chunks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_chunk_path(@chunk), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            chunk_path(@chunk),
            :method => 'delete',
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-danger' %>
  <a href="<%= @chunk.id %>/opencomments/new" class="btn">Comment</a>
  <a href="<%= @chunk.id %>/evaluations/new" class="btn">Evaluate</a>
</div>

<div class="row">
  <div class="span12">
    <%= raw Pygments.highlight(@chunk.comment, lexer: 'java') %>
    <%= raw Pygments.highlight(@chunk.code, lexer: 'java') %>
  </div>
</div>

<h3>Opencomments</h3>
<table class="table table-striped">
  <tr>
    <th>#</th>
    <th>Commenter</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @Opencomments.each do |opencomment| %>
  <tr>
    <td><%= opencomment.id %></td>
    <td><%= opencomment.commenter %></td>
    <td><%= opencomment.created_at %></td>
    <td><%= link_to 'Show', opencomment %></td>
    <td><%= link_to 'Edit', edit_opencomment_path(opencomment) %></td>
    <td><%= link_to 'Destroy', opencomment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<h3>Evaluations</h3>
<table class="table table-striped">
  <tr>
    <th>#</th>
    <th>User ID</th>
    <th>Created at</th>
    <th>Attr. 1</th>
    <th>Attr. 2</th>
    <th>Attr. 3</th>
    <th>Attr. 4</th>
    <th>Attr. 5</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @Evaluations.each do |evaluation| %>
  <tr>
    <td><%= evaluation.id %></td>
    <td><%= evaluation.user_id %></td>
    <td><%= evaluation.created_at %></td>
    <td><%= evaluation.attribute_one %>
    <td><%= evaluation.attribute_two %>
    <td><%= evaluation.attribute_three %>
    <td><%= evaluation.attribute_four %>
    <td><%= evaluation.attribute_five %>
    <td><%= link_to 'Show', evaluation %></td>
    <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
    <td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>